# 池化层

## 最大池化层和平均池化层

In [1]:
import torch
import torch.nn as nn
import d2l.torch as d2l

In [2]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1] - p_w +1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'mean':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [12]:
X = torch.tensor([[0.0, 1, 2], [3, 4, 5], [6, 7, 8]])
pool2d(X, (2, 2)), pool2d(X, (2,2), 'mean')

(tensor([[4., 5.],
         [7., 8.]]),
 tensor([[2., 3.],
         [5., 6.]]))

## 填充和步幅

In [15]:
X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [16]:
pool2d = nn.MaxPool2d(3)  # 默认步幅和大小相同
pool2d(X)

tensor([[[[10.]]]])

In [17]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)  # 也可以手动设定填充和步幅
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [19]:
pool2d = nn.MaxPool2d((2, 3), padding=(0, 1), stride=(2, 3))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 多个通道

In [34]:
X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
X = torch.cat((X, X+1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [35]:
pool2d = nn.MaxPool2d((3, 3), stride=2, padding=1)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])